INSERT INTO interests (id, name, category, icon) VALUES
    (gen_random_uuid(), 'Artificial Intelligence',        'Technology', 'brain'),
    (gen_random_uuid(), 'Machine Learning',               'Technology', 'cpu'),
    (gen_random_uuid(), 'Deep Learning',                  'Technology', 'network'),
    (gen_random_uuid(), 'Data Science',                   'Technology', 'chart-bar'),
    (gen_random_uuid(), 'Computer Vision',                'Technology', 'eye'),
    (gen_random_uuid(), 'Natural Language Processing',    'Technology', 'message'),
    (gen_random_uuid(), 'Robotics',                       'Technology', 'robot'),
    (gen_random_uuid(), 'Cybersecurity',                  'Technology', 'shield'),
    (gen_random_uuid(), 'Software Engineering',           'Technology', 'code'),
    (gen_random_uuid(), 'Cloud Computing',                'Technology', 'cloud'),
    (gen_random_uuid(), 'Internet of Things',             'Technology', 'wifi'),
    (gen_random_uuid(), 'Blockchain',                     'Technology', 'link'),
    (gen_random_uuid(), 'Augmented Reality',              'Technology', 'glasses'),
    (gen_random_uuid(), 'Virtual Reality',                'Technology', 'vr'),
    (gen_random_uuid(), 'Medicine',                       'Health',     'heart'),
    (gen_random_uuid(), 'Biomedical Engineering',         'Health',     'microscope'),
    (gen_random_uuid(), 'Bioinformatics',                 'Health',     'dna'),
    (gen_random_uuid(), 'Neuroscience',                   'Health',     'brain'),
    (gen_random_uuid(), 'Public Health',                  'Health',     'hospital'),
    (gen_random_uuid(), 'Pharmacy',                       'Health',     'pill'),
    (gen_random_uuid(), 'Nursing',                        'Health',     'user-md'),
    (gen_random_uuid(), 'Dentistry',                      'Health',     'tooth'),
    (gen_random_uuid(), 'Physiotherapy',                  'Health',     'walk'),
    (gen_random_uuid(), 'Mathematics',                    'Science',    'sigma'),
    (gen_random_uuid(), 'Physics',                        'Science',    'atom'),
    (gen_random_uuid(), 'Chemistry',                      'Science',    'flask'),
    (gen_random_uuid(), 'Biology',                        'Science',    'leaf'),
    (gen_random_uuid(), 'Astronomy',                      'Science',    'star'),
    (gen_random_uuid(), 'Environmental Science',          'Science',    'tree'),
    (gen_random_uuid(), 'Geology',                        'Science',    'mountain'),
    (gen_random_uuid(), 'Materials Science',              'Science',    'cube'),
    (gen_random_uuid(), 'Sustainability',                 'Science',    'recycle'),
    (gen_random_uuid(), 'Law',                            'Humanities', 'balance'),
    (gen_random_uuid(), 'Psychology',                     'Humanities', 'smile'),
    (gen_random_uuid(), 'Sociology',                      'Humanities', 'users'),
    (gen_random_uuid(), 'Philosophy',                     'Humanities', 'book'),
    (gen_random_uuid(), 'History',                        'Humanities', 'scroll'),
    (gen_random_uuid(), 'Literature',                     'Humanities', 'pen'),
    (gen_random_uuid(), 'Linguistics',                    'Humanities', 'language'),
    (gen_random_uuid(), 'Education',                      'Humanities', 'school'),
    (gen_random_uuid(), 'Economics',                      'Humanities', 'dollar'),
    (gen_random_uuid(), 'Business Administration',        'Humanities', 'briefcase'),
    (gen_random_uuid(), 'Accounting',                     'Humanities', 'calculator'),
    (gen_random_uuid(), 'Architecture',                   'Arts',       'building'),
    (gen_random_uuid(), 'Design',                         'Arts',       'palette'),
    (gen_random_uuid(), 'Visual Arts',                    'Arts',       'image'),
    (gen_random_uuid(), 'Music',                          'Arts',       'music'),
    (gen_random_uuid(), 'Theater',                        'Arts',       'mask'),
    (gen_random_uuid(), 'Cinema',                         'Arts',       'film'),
    (gen_random_uuid(), 'Photography',                    'Arts',       'camera'),
    (gen_random_uuid(), 'Agronomy',                       'Science',    'seedling'),
    (gen_random_uuid(), 'Veterinary Medicine',            'Health',     'paw'),
    (gen_random_uuid(), 'Nutrition',                      'Health',     'apple'),
    (gen_random_uuid(), 'Physical Education',             'Health',     'run'),
    (gen_random_uuid(), 'Social Work',                    'Humanities', 'handshake'),
    (gen_random_uuid(), 'International Relations',        'Humanities', 'globe'),
    (gen_random_uuid(), 'Journalism',                     'Humanities', 'newspaper'),
    (gen_random_uuid(), 'Advertising',                    'Humanities', 'megaphone'),
    (gen_random_uuid(), 'Public Relations',               'Humanities', 'share'),
    (gen_random_uuid(), 'Information Systems',            'Technology', 'database'),
    (gen_random_uuid(), 'Computer Engineering',           'Technology', 'monitor');
