server:
  port: 8761

eureka:
  instance:
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: true
    renewalPercentThreshold: 0.85

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
