// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCox2SIJip-wPQ28WpFUyYjZWIF3oJSl5w',
    appId: '1:302551957750:web:3d409d0ef08c12d5396cd7',
    messagingSenderId: '302551957750',
    projectId: 'desafio-final-05',
    authDomain: 'desafio-final-05.firebaseapp.com',
    storageBucket: 'desafio-final-05.firebasestorage.app',
    measurementId: 'G-Y3H9D8EHQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuBYVlp5l2Bd9uJkfOYQMptS_8gMQ6fZQ',
    appId: '1:302551957750:android:269babbf63fad65d396cd7',
    messagingSenderId: '302551957750',
    projectId: 'desafio-final-05',
    storageBucket: 'desafio-final-05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgME55tgi0azlECgGFqxC1gg18u78WYBY',
    appId: '1:302551957750:ios:b7e11d6dfe00f49c396cd7',
    messagingSenderId: '302551957750',
    projectId: 'desafio-final-05',
    storageBucket: 'desafio-final-05.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
